import { Component, OnInit, VERSION } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  name = 'Angular ' + VERSION.major;
  data: any = [];
  listDoctors: any = [];

  dataReduce: any = [];
  resultReduce: any = [];
  constructor() {
    this.data = [
      {
        codigoRetorno: 0,
        glosaRetorno: '',
        id: 0,
        folio: 0,
        medico: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '010052381-7',
          rutFormateado: null,
          email: null,
          direccion: null,
          latitud: 0,
          longitud: 0,
          comuna: null,
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: null,
          telefonoComercial1: null,
          telefonoComercial2: null,
          nombre: 'MATULIC MORENO VESNA',
          especialidad: null,
        },
        prestador: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '096942400-2',
          rutFormateado: null,
          email: null,
          direccion: 'NVA. PROVIDENCIA N°  1920',
          latitud: -33.425156,
          longitud: -70.61335,
          comuna: {
            codigoRetorno: 0,
            id: 0,
            nombre: 'PROVIDENCIA',
          },
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: '6004256000 - 24317200',
          telefonoComercial1: '6004256000',
          telefonoComercial2: '24317200',
          id: 0,
          correlativo: 0,
          nombre: 'MEGASALUD',
          imed: 'S',
          bonoWeb: 'S',
          cantMedicos: 0,
        },
        beneficiario: null,
        prestacion: null,
        fechaEmision: null,
        cobrado: 16920,
        bonificado: 13536,
        copago: 3384,
        favorito: 0,
        relacion: 0,
        user: null,
        origen: 0,
        excedentes: null,
        convenioPago: null,
        transaccion: null,
        excedentesMonto: 0,
        tipoBono: null,
      },
      {
        codigoRetorno: 0,
        glosaRetorno: '',
        id: 0,
        folio: 0,
        medico: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '010052381-7',
          rutFormateado: null,
          email: null,
          direccion: null,
          latitud: 0,
          longitud: 0,
          comuna: null,
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: null,
          telefonoComercial1: null,
          telefonoComercial2: null,
          nombre: 'MATULIC MORENO VESNA',
          especialidad: null,
        },
        prestador: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '096942400-2',
          rutFormateado: null,
          email: null,
          direccion: 'NVA. PROVIDENCIA N°  1920',
          latitud: -33.425156,
          longitud: -70.61335,
          comuna: {
            codigoRetorno: 0,
            id: 0,
            nombre: 'PROVIDENCIA',
          },
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: '6004256000 - 24317200',
          telefonoComercial1: '6004256000',
          telefonoComercial2: '24317200',
          id: 0,
          correlativo: 0,
          nombre: 'MEGASALUD',
          imed: 'S',
          bonoWeb: 'S',
          cantMedicos: 0,
        },
        beneficiario: null,
        prestacion: null,
        fechaEmision: null,
        cobrado: 16920,
        bonificado: 13536,
        copago: 3384,
        favorito: 0,
        relacion: 0,
        user: null,
        origen: 0,
        excedentes: null,
        convenioPago: null,
        transaccion: null,
        excedentesMonto: 0,
        tipoBono: null,
      },
      {
        codigoRetorno: 0,
        glosaRetorno: '',
        id: 0,
        folio: 0,
        medico: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '010052381-7',
          rutFormateado: null,
          email: null,
          direccion: null,
          latitud: 0,
          longitud: 0,
          comuna: null,
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: null,
          telefonoComercial1: null,
          telefonoComercial2: null,
          nombre: 'MATULIC MORENO VESNA',
          especialidad: null,
        },
        prestador: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '096942400-2',
          rutFormateado: null,
          email: null,
          direccion: 'NVA. PROVIDENCIA N°  1920',
          latitud: -33.425156,
          longitud: -70.61335,
          comuna: {
            codigoRetorno: 0,
            id: 0,
            nombre: 'PROVIDENCIA',
          },
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: '6004256000 - 24317200',
          telefonoComercial1: '6004256000',
          telefonoComercial2: '24317200',
          id: 0,
          correlativo: 0,
          nombre: 'MEGASALUD',
          imed: 'S',
          bonoWeb: 'S',
          cantMedicos: 0,
        },
        beneficiario: null,
        prestacion: null,
        fechaEmision: null,
        cobrado: 16920,
        bonificado: 13536,
        copago: 3384,
        favorito: 0,
        relacion: 0,
        user: null,
        origen: 0,
        excedentes: null,
        convenioPago: null,
        transaccion: null,
        excedentesMonto: 0,
        tipoBono: null,
      },
      {
        codigoRetorno: 0,
        glosaRetorno: '',
        id: 1,
        folio: 0,
        medico: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '017087260-6',
          rutFormateado: null,
          email: null,
          direccion: null,
          latitud: 0,
          longitud: 0,
          comuna: null,
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: null,
          telefonoComercial1: null,
          telefonoComercial2: null,
          nombre: 'SHERTZER BYRT CAMILA',
          especialidad: null,
        },
        prestador: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '096942400-2',
          rutFormateado: null,
          email: null,
          direccion: 'NVA. PROVIDENCIA N°  1920',
          latitud: -33.425156,
          longitud: -70.61335,
          comuna: {
            codigoRetorno: 0,
            id: 0,
            nombre: 'PROVIDENCIA',
          },
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: '6004256000 - 24317200',
          telefonoComercial1: '6004256000',
          telefonoComercial2: '24317200',
          id: 0,
          correlativo: 0,
          nombre: 'MEGASALUD',
          imed: 'S',
          bonoWeb: 'S',
          cantMedicos: 0,
        },
        beneficiario: null,
        prestacion: null,
        fechaEmision: null,
        cobrado: 16920,
        bonificado: 13536,
        copago: 3384,
        favorito: 0,
        relacion: 0,
        user: null,
        origen: 0,
        excedentes: null,
        convenioPago: null,
        transaccion: null,
        excedentesMonto: 0,
        tipoBono: null,
      },
      {
        codigoRetorno: 0,
        glosaRetorno: '',
        id: 0,
        folio: 0,
        medico: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '007463897-K',
          rutFormateado: null,
          email: null,
          direccion: null,
          latitud: 0,
          longitud: 0,
          comuna: null,
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: null,
          telefonoComercial1: null,
          telefonoComercial2: null,
          nombre: 'CARRASCO ALARCON OLGA',
          especialidad: null,
        },
        prestador: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '096942400-2',
          rutFormateado: null,
          email: null,
          direccion: 'NVA. PROVIDENCIA N°  1920',
          latitud: -33.425156,
          longitud: -70.61335,
          comuna: {
            codigoRetorno: 0,
            id: 0,
            nombre: 'PROVIDENCIA',
          },
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: '6004256000 - 24317200',
          telefonoComercial1: '6004256000',
          telefonoComercial2: '24317200',
          id: 0,
          correlativo: 0,
          nombre: 'MEGASALUD',
          imed: 'S',
          bonoWeb: 'S',
          cantMedicos: 0,
        },
        beneficiario: null,
        prestacion: null,
        fechaEmision: null,
        cobrado: 16920,
        bonificado: 13536,
        copago: 3384,
        favorito: 0,
        relacion: 0,
        user: null,
        origen: 0,
        excedentes: null,
        convenioPago: null,
        transaccion: null,
        excedentesMonto: 0,
        tipoBono: null,
      },
      {
        codigoRetorno: 0,
        glosaRetorno: '',
        id: 0,
        folio: 0,
        medico: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '018392973-9',
          rutFormateado: null,
          email: null,
          direccion: null,
          latitud: 0,
          longitud: 0,
          comuna: null,
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: null,
          telefonoComercial1: null,
          telefonoComercial2: null,
          nombre: 'OLEA MUÑOZ ANTONIA PAZ',
          especialidad: null,
        },
        prestador: {
          codigoRetorno: 0,
          glosaRetorno: '',
          rut: '096942400-2',
          rutFormateado: null,
          email: null,
          direccion: 'NVA. PROVIDENCIA N°  1920',
          latitud: -33.425156,
          longitud: -70.61335,
          comuna: {
            codigoRetorno: 0,
            id: 0,
            nombre: 'PROVIDENCIA',
          },
          ciudad: null,
          region: null,
          telefonoParticular: null,
          telefonoCelular: null,
          telefonoComercial: '6004256000 - 24317200',
          telefonoComercial1: '6004256000',
          telefonoComercial2: '24317200',
          id: 0,
          correlativo: 0,
          nombre: 'MEGASALUD',
          imed: 'S',
          bonoWeb: 'S',
          cantMedicos: 0,
        },
        beneficiario: null,
        prestacion: null,
        fechaEmision: null,
        cobrado: 16920,
        bonificado: 13536,
        copago: 3384,
        favorito: 0,
        relacion: 0,
        user: null,
        origen: 0,
        excedentes: null,
        convenioPago: null,
        transaccion: null,
        excedentesMonto: 0,
        tipoBono: null,
      },
    ];
  }

  ngOnInit() {
    // console.log('this.data', this.data);
    this.extractDoctors();
  }

  extractDoctors() {
    this.data.forEach((item, index) => {
      const objBono = Object.assign(item['prestador'], {
        typePrestador: 'prestador',
      });
      const objPrestador = Object.assign(item['medico'], {
        typePrestador: 'medico',
      });

      console.log('extractDoctors', {
        item: item.medico.rut,
        index: index,
      });

      // verificar si el rut del doctor ya existe
      // this.listDoctors.push(item.prestador);
    });
    const reduce = this.groupArrayOfObjects(this.listDoctors, 'rut');
    // console.log('********', reduce);
  }

  groupArrayOfObjects(list: any, key: any) {
    /*console.log('groupArrayOfObjects', {
      list: list,
      key: key,
    });*/
    return list.reduce(function (rv, x) {
      (rv[x[key]] = rv[x[key]] || []).push(x);
      return rv;
    }, {});
  }
}
